<?php
    define('DB_HOST', 'localhost');
    define('DB_USER', 'root');
    define('DB_PASS', 'mysql');
    define('DB_NAME', 'bpdemo');
    define('APP_BANNER', 'BP Services Portal');
    define('ERROR_DB_CONNECT', 'Error: Cant connect to Database');
    define('DEF_YEAR', '2015');
    define('DEF_FIRST_YEAR', '1990');
    define('DEF_LAST_YEAR', '2040');
    define('SUCCESS', 0);
    define('FAIL', true);
    define('SKIP_NTWK_API', true);
    define('ERROR_SVC_DB', "Can't get info from DB");
    define('ERROR_SVC_CREATE', "Failed to create circuit");

    $site_type = array(
        "Radio",
        "Data-Centre",
        "EPC",
        "Exchange",
        "Office",
        "Residential",
        "Warehouse",
        "Factory"
    );
    
    $state_list = array(
        "VIC",
        "NSW",
        "SA",
        "WA",
        "NT",
        "ACT",
        "QLD",
        "TAS",
        "---",
        "Barcelona",
        "Valencia",
        "Alicante",
        "Sevilla",
        "Málaga",
        "Murcia",
        "Cádiz",
        "Biscay",
        "La Coruña",
        "Balearic Islands",
        "Las Palmas",
        "Asturias",
        "Santa Cruz de Tenerife",
        "Zaragoza",
        "Pontevedra",
        "Granada",
        "Tarragona",
        "Córdoba",
        "Girona",
        "Gipuzkoa",
        "Toledo",
        "Almería",
        "Badajoz",
        "Jaén",
        "Navarre",
        "Castellón",
        "Cantabria",
        "Valladolid",
        "Ciudad Real",
        "Huelva",
        "León",
        "Lleida",
        "Cáceres",
        "Albacete",
        "Burgos",
        "Lugo",
        "Salamanca",
        "Ourense",
        "La Rioja",
        "Álava",
        "Guadalajara",
        "Huesca",
        "Cuenca",
        "Zamora",
        "Palencia",
        "Ávila",
        "Segovia",
        "Teruel",
        "Soria",
        "Ceuta",
        "Melilla"
    );
    
    date_default_timezone_set('Australia/Melbourne');
    
    $country_list = array(
                "Australia",
                "Spain",
                "------------",
		"Afghanistan",
		"Albania",
		"Algeria",
		"Andorra",
		"Angola",
		"Antigua and Barbuda",
		"Argentina",
		"Armenia",
		"Australia",
		"Austria",
		"Azerbaijan",
		"Bahamas",
		"Bahrain",
		"Bangladesh",
		"Barbados",
		"Belarus",
		"Belgium",
		"Belize",
		"Benin",
		"Bhutan",
		"Bolivia",
		"Bosnia and Herzegovina",
		"Botswana",
		"Brazil",
		"Brunei",
		"Bulgaria",
		"Burkina Faso",
		"Burundi",
		"Cambodia",
		"Cameroon",
		"Canada",
		"Cape Verde",
		"Central African Republic",
		"Chad",
		"Chile",
		"China",
		"Colombi",
		"Comoros",
		"Congo (Brazzaville)",
		"Congo",
		"Costa Rica",
		"Cote d'Ivoire",
		"Croatia",
		"Cuba",
		"Cyprus",
		"Czech Republic",
		"Denmark",
		"Djibouti",
		"Dominica",
		"Dominican Republic",
		"East Timor (Timor Timur)",
		"Ecuador",
		"Egypt",
		"El Salvador",
		"Equatorial Guinea",
		"Eritrea",
		"Estonia",
		"Ethiopia",
		"Fiji",
		"Finland",
		"France",
		"Gabon",
		"Gambia, The",
		"Georgia",
		"Germany",
		"Ghana",
		"Greece",
		"Grenada",
		"Guatemala",
		"Guinea",
		"Guinea-Bissau",
		"Guyana",
		"Haiti",
		"Honduras",
		"Hungary",
		"Iceland",
		"India",
		"Indonesia",
		"Iran",
		"Iraq",
		"Ireland",
		"Israel",
		"Italy",
		"Jamaica",
		"Japan",
		"Jordan",
		"Kazakhstan",
		"Kenya",
		"Kiribati",
		"Korea, North",
		"Korea, South",
		"Kuwait",
		"Kyrgyzstan",
		"Laos",
		"Latvia",
		"Lebanon",
		"Lesotho",
		"Liberia",
		"Libya",
		"Liechtenstein",
		"Lithuania",
		"Luxembourg",
		"Macedonia",
		"Madagascar",
		"Malawi",
		"Malaysia",
		"Maldives",
		"Mali",
		"Malta",
		"Marshall Islands",
		"Mauritania",
		"Mauritius",
		"Mexico",
		"Micronesia",
		"Moldova",
		"Monaco",
		"Mongolia",
		"Morocco",
		"Mozambique",
		"Myanmar",
		"Namibia",
		"Nauru",
		"Nepal",
		"Netherlands",
		"New Zealand",
		"Nicaragua",
		"Niger",
		"Nigeria",
		"Norway",
		"Oman",
		"Pakistan",
		"Palau",
		"Panama",
		"Papua New Guinea",
		"Paraguay",
		"Peru",
		"Philippines",
		"Poland",
		"Portugal",
		"Qatar",
		"Romania",
		"Russia",
		"Rwanda",
		"Saint Kitts and Nevis",
		"Saint Lucia",
		"Saint Vincent",
		"Samoa",
		"San Marino",
		"Sao Tome and Principe",
		"Saudi Arabia",
		"Senegal",
		"Serbia and Montenegro",
		"Seychelles",
		"Sierra Leone",
		"Singapore",
		"Slovakia",
		"Slovenia",
		"Solomon Islands",
		"Somalia",
		"South Africa",
		"Spain",
		"Sri Lanka",
		"Sudan",
		"Suriname",
		"Swaziland",
		"Sweden",
		"Switzerland",
		"Syria",
		"Taiwan",
		"Tajikistan",
		"Tanzania",
		"Thailand",
		"Togo",
		"Tonga",
		"Trinidad and Tobago",
		"Tunisia",
		"Turkey",
		"Turkmenistan",
		"Tuvalu",
		"Uganda",
		"Ukraine",
		"United Arab Emirates",
		"United Kingdom",
		"United States",
		"Uruguay",
		"Uzbekistan",
		"Vanuatu",
		"Vatican City",
		"Venezuela",
		"Vietnam",
		"Yemen",
		"Zambia",
		"Zimbabwe"
	);
?>